"colorscheme darkblue
"clipboard共有
set guioptions+=a
"tab名いじったのでtabのgui表示をoff
set guioptions-=e
""insert modeから離れるときにIME off
"set noimdisable
"set iminsert=2

"色設定
colorscheme inkpot
hi Identifier guifg=LightSkyBlue3
hi Number guifg=Red
hi Type guifg=DarkOliveGreen3
hi string guibg=NONE guifg=LightGoldenrod2
hi Comment guifg=MediumPurple4
hi LineNr guifg=Grey30 guibg=NONE
hi Normal guifg=LightGray

"下線設定
set cursorline
hi CursorLine gui=underline guifg=NONE guibg=NONE
hi CursorLineNr guifg=NavyBlue guibg=White

"NERDTree color setting
hi NERDTreeBookmarksLeader  guifg=DeepSkyBlue3
hi NERDTreeBookmark guifg=DarkOliveGreen3

"必要ならneocompleteの補完リストの色設定
"hi Pmenu guibg=LightBlue
"hi PmenuSel guibg=red
"hi PmenuSbar guibg=LightBlue

let s:month = strftime("%b")
let s:date = strftime("%d")
if (s:month == 5) && (s:date == 4)
    "" Birthday
    hi StatusLine guifg=Khaki3 guibg=DarkGoldenrod
    hi WildMenu guifg=DarkGoldenrod guibg=Khaki3
elseif (s:month == 3) || (s:month == 4 ) || (s:month == 5)
    "" Spring
    hi StatusLine guifg=Pink1 guibg=DarkMagenta
    hi WildMenu guifg=DarkMagenta guibg=Pink1
elseif (s:month == 6) || (s:month == 7 ) || (s:month == 8)
    "" Summer
    hi StatusLine guifg=GreenYellow guibg=DodgerBlue2
    hi WildMenu guifg=DodgerBlue2 guibg=GreenYellow
elseif (s:month == 9) || (s:month == 10 ) || (s:month == 11)
    "" Fall
    hi StatusLine guifg=Yellow3 guibg=DarkRed
    hi WildMenu guifg=DarkRed guibg=Yellow3
elseif (s:month == 12) || (s:month == 1 ) || (s:month == 2)
    "" Winter
    hi StatusLine guifg=LightSkyBlue3 guibg=NavyBlue
    hi WildMenu guifg=NavyBlue guibg=LightSkyBlue3
else
    hi StatusLine guifg=Grey62 guibg=Grey15
    hi WildMenu guifg=Grey15 guibg=Grey62
endif
"default ... hi StatusLine ??


"ビープ音を消す
set visualbell t_vb=

"透過
autocmd local GUIEnter * set transparency=240 "0~255?

function! Hide(...)
    let l:tra = &transparency
    let l:time = get(a:,1,5)
    set transparency=1
    execute "sleep " . l:time
    execute "set transparency=" . l:tra
endfunction

"local設定ファイル
let s:localgrc = g:vimdir . 'rcdir/gvimrc.mine'
if filereadable(s:localgrc)
    execute "source " . s:localgrc
endif
