"vim script encording setting
" encoding setting for vim system
set encoding=utf-8
" encoding setting for current buffer
set fileencoding=utf-8
" encoding setting for all buffer
set fileencodings=utf-8
" encoding setting for vim script
scriptencoding utf-8

augroup gLocal
    autocmd!
augroup END

"GUI系基本設定 {{{
"clipboard共有
set guioptions+=a
"tab名いじったのでtabのgui表示をoff
set guioptions-=e
""insert modeから離れるときにIME off
"set noimdisable
"set iminsert=2
"gui のツールバー非表示
set guioptions-=T

"ビープ音を消す
set visualbell t_vb=

"}}}

" "色設定
let s:color_file = g:vimdir . "rcdir/gvimrc_color.vim"
if filereadable(s:color_file)
    execute "source " . s:color_file
endif

"その他 GUI 設定 {{{
"透過
autocmd gLocal GUIEnter * set transparency=240 "0~255?

function! Hide(...)
    let l:tra = &transparency
    let l:time = get(a:,1,5)
    set transparency=1
    execute "sleep " . l:time
    execute "set transparency=" . l:tra
endfunction

"local設定ファイル
let s:localgrc = g:vimdir . 'rcdir/gvimrc.mine'
if filereadable(s:localgrc)
    execute "source " . s:localgrc
endif

"}}}

