" encoding setting
" encoding setting for vim system
set encoding=utf-8
" encoding setting for current buffer (when make a new file?)
set fileencoding=utf-8
" available encoding settings for all buffer
set fileencodings=utf-8
" encoding setting for vim script
scriptencoding utf-8

" viとの互換性をとらない
set nocompatible
" 文字の色づけ ... onだと現状の設定を破棄する。詳しくは:h :syntax-on
syntax enable

if exists('$VIM_TERMINAL') || $SHELL_INFO[-1:]=='v'
    echoerr 'Warning!! vim is already opened!!'
endif

if 0
    augroup viminitlocal
        autocmd!
        autocmd SourcePre * call meflib#debug#debug_log(expand('<afile>'), 'source pre')
        autocmd SourcePost * call meflib#debug#debug_log(expand('<afile>'), 'source post')
    augroup END
endif

try
    let s:vimdir = meflib#basic#get_conf_dir()
catch
    echomsg 'meflib not found. So, no files are sourced.'
endtry

function! s:source_file(filename) abort
    if exists('s:vimdir') && filereadable(s:vimdir..a:filename)
        execute 'source '..s:vimdir..a:filename
        return 1
    endif
    return 0
endfunction

" local settings before source vimrcs
call s:source_file('rcdir/vimrc_mine.pre')
" option settings
call s:source_file('rcdir/vimrc_options.vim')
" map(key) settings
call s:source_file('rcdir/vimrc_maps.vim')
" simple commands and short functions
call s:source_file('rcdir/vimrc_commands.vim')
" auto command settings
call s:source_file('rcdir/vimrc_autocmds.vim')
" status line setting
call s:source_file('rcdir/vimrc_statusline.vim')
" tab line setting
call s:source_file('rcdir/vimrc_tabline.vim')
" vimPlug (plugin manager) setting
call s:source_file('rcdir/vimrc_vimplug.vim')
" color settings
if !has('gui_running') && (&t_Co == 256)
    if !s:source_file('rcdir/vimrc_color.vim')
        " In case vim doesn't source vimrc_color.vim
        colorscheme evening
        highlight Normal ctermbg=0 guibg=Black
        highlight DiffAdd ctermfg=15 ctermbg=4 guifg=White guibg=DarkBlue
        highlight DiffChange ctermfg=15 ctermbg=5 guifg=White guibg=DarkMagenta
        highlight DiffDelete ctermfg=15 ctermbg=6 guifg=White guibg=DarkCyan
        highlight DiffText ctermfg=15 ctermbg=9 guifg=White guibg=Red
    endif
endif
" local settings after source vimrcs
call s:source_file('rcdir/vimrc_mine.post')

