#! /usr/bin/env python

import os
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('environ',help='environment value')
args = parser.parse_args()

sep = os.pathsep

if sep in args.environ:
    envar = args.environ
    envar = envar.replace(sep,sep+'\n')
    print(envar)

elif args.environ in os.environ:    # key check
    envar = os.environ[args.environ]
    envar = envar.replace(sep,sep+'\n')
    print(envar)

else:
    #print('please input environmental variable')
    print(args.environ)

