
# toml 用 syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# dark powered 補完plugin
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
"{{{ "deoplete
let g:deoplete#enable_at_startup = 1
inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
inoremap <expr><S-tab> pumvisible() ? "\<C-p>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<S-tab>"

""" test
autocmd deinLocal FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd deinLocal FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd deinLocal FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd deinLocal FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd deinLocal FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
" auto close preview window.
autocmd deinLocal CompleteDone * silent! pclose!

"}}}
'''

# vim でsnippet を使う用の plugin (framework?)
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_ft = 'snippet'

# vim script 用補完 plugin
[[plugins]]
repo = 'Shougo/neco-vim'
on_i = 1
on_ft = 'vim'

# syntax file から補完候補を作成
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

# https://github.com/Shougo/deoplete.nvim/wiki/Completion-Sources

# c言語用補完 plugin
[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_source = ['deoplete.nvim']
on_ft = 'c'

# python 用補完 plugin
[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_source = ['deoplete.nvim']
on_ft = 'python'

# vimの編集履歴を表示／適用してくれる plugin
[[plugins]]
repo = 'sjl/gundo.vim'
on_i = 1
hook_source = '''
" {{{ "Gundo
if has('python3')
    let g:gundo_prefer_python3 = 1
endif
nnoremap <silent> <Leader>u :GundoToggle<CR>
" }}}
'''

