
# Project Sekai inspired plugin
[[plugins]]
repo = 'MeF0504/untitled.vim'

# colorscheme
[[plugins]]
repo = 'MeF0504/vim-monoTone'

# window のresize, 移動用plugin
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
""" sinresizer {{{
let g:winresizer_finish_with_escape = 0
let g:winresizer_start_key = '<leader>w'
let g:winresizer_vert_resize = 5
let g:winresizer_horiz_resize = 2
""" }}}
'''

# カッコの強調を，処理を落として高速化
# https://itchyny.hatenablog.com/entry/2016/03/30/210000
[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
" {{{
" デフォルト機能をoff
let g:loaded_matchparen = 1
" デフォルトのhighlightをoff
let g:parenmatch_highlight = 0
" }}}
'''

